### ISSUE TITLE
Two __init__ methods will only take the latest version

### ISSUE THREAD

**Issue by mertzjames** [r0meroh/CSE_CLUB_cpp_to_python_workshop#1]
https://github.com/r0meroh/CSE_CLUB_cpp_to_python_workshop/blob/694efc945adb7fba8a989eef72a8d790504d60ea/person.py#L16

If you try to create a person object without anything passed in as the params, then you'll get an error.  You should do this instead:

```python
    def __init__(self, name="", age=0):
        self.name = name
        self.age = age
```

**Comment by r0meroh** [comment]
Thank you so much for the feedback :) I am unsure as what you mean though. The constructor definition is overloaded so it has both a default constructor and a parametric one. Here is a screen shot of an empty instance being created followed by a parameter filled instances. Afterwards another empty instance is created just to make sure the program recognizes to go back to the empty constructor declaration.

If I am misunderstanding please let me know, as I am always trying to improve :) The main reason for the overloading was to explain overloading in a workshop that this code was created in.

![image](https://user-images.githubusercontent.com/45727884/85068493-5b50ef00-b167-11ea-92ae-ec5947fe6448.png)

**Comment by mertzjames** [comment]
So in Python, there really isn't a concept of "overloading" as you have in other languages.  Using your code, the first `__init__` is overridden by the second.  I tested this out on my Python install (Python 3.8) and indeed did get an error as it was prompting for 2 inputs.  

In the example that you have above, you're actually calling the second `__init__`.  Even though your input has nothing entered from the user, you're actually getting an empty string and that empty string is what is passed into the `__init__`.  I hope that makes sense for ya.

**Comment by r0meroh** [comment]
Oh, ok, I understand what you mean now. And you are right that it is technically not empty since input by default is passed as a string. Just curious, how did you manage to pass an empty instance? I ask, cause the code is setup to always pass a string when the user is prompted.

**Comment by mertzjames** [comment]
I copied the code for the class into the intrepreter and then tried to instantiate the class without arguments ;)
